comment/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'comment'
urlpatterns = [
    url(r'^upload_comment/$', views.upload_comment, name='upload_comment'),

]

likes/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'likes'

urlpatterns = [
    url(r'^like_change', views.like_change, name='like_change'),
]

myblog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'myblog'
urlpatterns = [
    url(r'^$', views.blog_list, name='blog_list'),
    url(r'^(?P<blog_pk>[0-9]+)/$', views.blog_detail, name='blog_detail'),
    url(r'^type/(?P<blog_type_pk>[0-9]+)/$', views.blogs_with_type, name='blogs_with_type'),
    url(r'^date/(?P<year>[0-9]+)/(?P<month>[0-9]+)',views.blogs_with_date, name ='blogs_with_date')

]
#将根urlconf指向polls.urls模块
#该url函数传递了四个参数，两个必须：route 和view ，以及两个可选kwargs和name
    #route参数：使用正则表达式进行捕获和匹配
        # 术语 “regex” 是正则表达式 “regular expression” 的缩写，是匹配字符串的一段语法，像这里例子的是 url 匹配模式。Django 从列表的第一个正则表达式开始，按顺序匹配请求的 URL，直到找到与之匹配的。
        # 注意，这些正则表达式不会去匹配 GET 和 POST 请求的参数值，或者域名。
        # 比如 https://www.example.com/myapp/ 这个请求，URLconf 会找 myapp/；https://www.example.com/myapp/?page=3 这个请求，URLconf 同样只会找 mysqpp/。
        #这些正则表达式在 URLconf 模块加载后的第一时间就被编译了
    #view参数
        # 当Django发现一个正则表达式匹配时，Django就会调用指定的视图函数，
        # HttpRequest对象作为第一个参数，正则表达式捕获的值作为其他参数。如果正则使用简单捕获，值会作为位置参数传递；
        # 如果使用命名捕获，值会作为关键字传递。我们稍后会给出一个例子。
    # name参数
        #命名你的URL可以让你在Django的别处明白引用的是什么，特别是在模版里。
        #这个强大的特性允许你在项目里对一个文件操作就能对URL模式做全局改变。

user/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('login/', views.login_user, name='login_user'),
    path('login_for_modal/', views.login_for_modal, name='login_for_modal'),
    path('register/', views.register_user, name='register_user'),
    path('logout/', views.logout, name="logout"),
    path('user_info/', views.user_info, name="user_info"),
    path('change_nickname/',views.change_nickname,name = "change_nickname"),
    path('bind_email/',views.bind_email,name = "bind_email"),
    path('send_verification_code/',views.send_verification_code,name = "send_verification_code"),
    path('change_password/',views.change_password,name = "change_password"),
    path('forgot_password/',views.forgot_password,name = "forgot_password"),
]

myblog/models.py
from django.db import models

from django.contrib.auth.models import User
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse  #反向解析
from read_statistics.models import ReadNumExpendMethod,ReadDetail
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit
# Create your models here.



class BlogType(models.Model):
    type_name = models.CharField(max_length=15)  #类型标题

    def __str__(self):  #将一个类的示例转换为字符串的形式
        return self.type_name

class Blog(models.Model,ReadNumExpendMethod):
    title = models.CharField(max_length=50)  #文章标题
    blog_type = models.ForeignKey(BlogType,on_delete=models.CASCADE ,related_name="blog_blog")
    #外键管理
    content = RichTextUploadingField()  #内容，使用长文本字段
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    read_details = GenericRelation(ReadDetail)
    # read_num = models.IntegerField(default=0)  #阅读计数字段
    created_time = models.DateTimeField(auto_now_add = True,)  #auto_now_add 首次创建对象时自动将字段设置为现在
    last_update_time = models.DateTimeField(auto_now=True,) #auto_now  用于创建和修改字段
    #给文章博客添加封面
    avator =ProcessedImageField(
        #数据库中保存的实际上是封面的对应地址
        upload_to='avator/',
        processors=[ResizeToFit(width=140)],
        format='JPEG',
        options={'quality': 100},
        #设置默认的封面
        default='/avator/default.jpg',
    )
    def get_url(self):
        return reverse('myblog:blog_detail',kwargs={'blog_pk':self.pk})
    
    def get_email(self):
        return self.author.email

    def __str__(self):
        return "<Blog: %s>"%self.title


    class Meta:
        ordering =['-created_time']  #


    

myblog/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator
from django.conf import settings
from django.db.models import Count
from django.contrib.contenttypes.models import ContentType
from datetime import datetime
from read_statistics.utils import read_statistics_once_read
from .models import Blog,BlogType
from comment.models import Comment
from comment.forms import CommentForm
from user.forms import LoginForm
# Create your views here.



#一个公共函数，提取出每一个视图函数的公共部分
def get_blog_lists_common_data(blogs_all_list,request):
    paginator = Paginator(blogs_all_list, settings.BLOGS_NUM_OF_EACH_PAGE)  # 实例化分页器，每十页进行分页
    page_num = request.GET.get('page', 1)  # 获取url页码参数，在python中，get请求得到是一个请求参数的字典，访问其中的'page'属性，如果没有给定值，就默认page属性的值为1
    page_of_blogs = paginator.get_page(page_num)  # 该函数会对参数类型进行判断和转换，一旦出错，会自动默认为1
    current_page_num = page_of_blogs.number  # 获取当前页码
    # 获取当前页码的前后两页的页码范围
    page_range = list(range(max(current_page_num - 2, 1), current_page_num)) + list(
        range(current_page_num, min(current_page_num + 2, paginator.num_pages) + 1))

    # 加上省略页码标记
    if page_range[0] - 1 >= 2:
        page_range.insert(0, '...')
    if paginator.num_pages - page_range[-1] >= 2:
        page_range.append('...')

    # 加上首页和尾页
    if page_range[0] != 1:
        page_range.insert(0, 1)
    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)


    #获取博客分类的对应博客数量


    # blog_types = BlogType.objects.all()
    # blog_type_list=[]
    # for blog_type in blog_types:
    #     blog_type.blog_count=Blog.objects.filter(blog_type=blog_type).count()   #利用python语言规则：实例化对象，增加一个count数量属性
    #     blog_type_list.append(blog_type)

    #获取日期归档对应的博客数量
    blog_dates = Blog.objects.dates('created_time', 'month', order="DESC")
    blog_dates_dict ={}
    for blog_date in blog_dates:
        blog_date_count = Blog.objects.filter(created_time__year = blog_date.year,
                            created_time__month = blog_date.month).count()
        blog_dates_dict[blog_date]=blog_date_count


    context = {}
    # context['blogs'] = page_of_blogs.object_list
    context['page_of_blogs'] = page_of_blogs
    context['blog_types'] =  BlogType.objects.annotate(blog_count = Count('blog_blog'))  #解析出来的是一条SQL语句，只有在用的时候，才会执行SQL语句，将数据放入内存,会减轻服务器的压力
    context['page_range'] = page_range
    context['blog_dates'] = blog_dates_dict  #
    return context

def blog_list(request):
    blogs_all_list= Blog.objects.all()

    context = get_blog_lists_common_data(blogs_all_list,request)
    # 用于计算一共有几篇博客context['blogs_count'] =Blog.objects.all().count()
    return render(request, template_name='myblog/blog_list.html', context=context)

def blog_detail(request,blog_pk):
    context = {}
    blog= Blog.objects.get(pk=blog_pk)
    #计算统计博客的阅读数量
    read_cookie_key = read_statistics_once_read(request,blog)
    
    #获取这篇博客的相关评论
    blog_content_type = ContentType.objects.get_for_model(blog)  #获得评论对象的模型
    # comments = Comment.objects.filter(content_type = blog_content_type,object_id = blog.pk,parent=None)
    

    #假设这一篇博客是1/26
    context['previous_blog']  = Blog.objects.filter(created_time__gt=blog.created_time).last()  #获得紧挨着的上一篇博客1/27
    context['next_blog'] = Blog.objects.filter(created_time__lt=blog.created_time).first()  # 获得紧挨着的下一篇博客1/25
    context['blog']=blog
    # context['login_form'] = LoginForm()
    # context['comments'] = comments.order_by('-comment_time')
    # context['comment_count'] = Comment.objects.filter(content_type = blog_content_type,object_id = blog.pk).count()
    # context['comment_form']=CommentForm(initial={'content_type': blog_content_type.model,'object_id':blog_pk,'reply_comment_id':0})   #显示评论的表单
    response=render(request, template_name='myblog/blog_detail.html', context=context)   #响应,会自动包含用户信息，详细见settings---Templates
    response.set_cookie( read_cookie_key, 'true')  #阅读cookie的标记，默认是在退出浏览器之前，维持一次通话
    return response


def blogs_with_type(request,blog_type_pk):
    context = {}
    blog_type= get_object_or_404(BlogType,pk=blog_type_pk)  #主键等于参数传进来的值
    blogs_type_list =Blog.objects.filter(blog_type=blog_type)  #进行筛选
    context = get_blog_lists_common_data(blogs_type_list,request)
    context['blog_type'] = blog_type
    return render(request,template_name='myblog/blogs_with_type.html',context=context)

def blogs_with_date(request,year,month):
    context = {}
    # blog_type = get_object_or_404(BlogType, pk=blog_type_pk)  # 主键等于参数传进来的值
    blogs_date_list = Blog.objects.filter(created_time__year=year,created_time__month=month)  # 进行筛选

    context=get_blog_lists_common_data(blogs_date_list,request)
    context['blogs_with_date'] = '%s年%s月' %(year,month)
    return render(request,template_name='myblog/blogs_with_date.html', context=context)

myblog/templates/myblog/blog_detail.html
{#使用模板嵌套进行重新编写#}
{% extends 'base.html' %}


{% load static %}
{% load comment_tags%}
{% load likes_tags %}
{% block header_content %}
    <link rel ="stylesheet" href="{% static 'myblog/style/blog.css' %}">
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock%}


{% block title %}
    {#页面标题，填充题目#}
    {{blog.title}}
{% endblock %}

{% block nav_blog_active %}active{%endblock%}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <h1>{{ blog.title }}</h1>
                <ul class="block-info-description">
                    <li>作者：{{blog.author}}</li>
                    <li>分类：
                        <a href="{%url 'myblog:blogs_with_type' blog.blog_type.pk%}">{{blog.blog_type}}</a>
                    </li>
                    <li>发表日期：{{blog.created_time|date:"y-m-d H:i:s"}}</li>
                    <li>阅读量({{blog.get_read_num}})</li>
                    <li>评论数({% get_comment_count blog %})</li>
                     <!--  “|”的意思是过滤器 ,truncate:缩短，只显示前几个字符内容,一个汉字两个字符-->
                </ul>
                <div class="blog-content"> {{ blog.content |safe}}</div> {#safe 模式保证了html标签的正常使用和转换#}
                <div class="like" onclick="like_change(this,'{% get_content_type blog %}',{{ blog.pk }})">
                    <span class="glyphicon glyphicon-thumbs-up {% get_like_status blog %}"></span>
                    <span class="liked-num">{% get_like_count blog %}</span>
                    <span>喜欢</span>
                </div>
                <div class="blog-more">
                    <nav aria-label="...">
                      <ul class="pager">
                          {% if previous_blog %}
                            <li class="previous"><a href="{% url 'myblog:blog_detail' previous_blog.pk %}"><span aria-hidden="true">&larr;</span>上一篇</a></li>
                          {% else %}
                            <li class="previous disabled"><a href="#"><span aria-hidden="true">&larr;</span> 上一篇</a></li>
                          {% endif %}

                          {% if next_blog %}
                            <li class="next"><a href="{% url 'myblog:blog_detail' next_blog.pk %}">下一篇<span aria-hidden="true">&rarr;</span></a></li>
                          {% else %}
                            <li class="next disabled"><a href="#"><span aria-hidden="true">&rarr;</span> Older</a></li>
                          {% endif %}


                      </ul>
                    </nav>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <div class="comment-area">
                    <h3 class="comment-area-title">提交评论</h3>
                    {% if user.is_authenticated %}   {#  判断用户是否进行了登录  ：is_authenticated#}
                        <form  id="comment_form"action="{% url 'comment:upload_comment' %}" method="POST" style="overflow:hidden">
                            <label for="comment-text">{{user.get_nickname_or_username}}已登录，欢迎评论~</label>
                            <div id="reply_content_container" style="display:none;">
                                <p style="border-bottom: 1px dashed #ccc;padding-bottom: 0.3em;">回复：</p>
                                <div id="reply_content" >

                                </div>
                            </div>
                            {% csrf_token %}
                            {#去除label的方法，将字段进行遍历#}
                            {% get_comment_form blog as comment_form %}
                            {% for field in comment_form %}
                                {{ field }}
                            {% endfor %}
                            <span  id="comment_error" class="text-danger pull-left"></span>
                            <input class="btn btn-info pull-right" type="submit" value="评论提交" style="float:right">
                        </form>
                    {% else %}
                        未登录，登录之后方可评论~
                        <a class="btn btn-primary" href ="{% url 'login_user' %}?from={{ request.get_full_path }}">登录</a>  {#   ？获取一个包含了相关数据的相对路径(get方式) #}
                        <span> or </span>
                        <a class="btn btn-danger" href ="{% url 'register_user' %}?from={{ request.get_full_path }}">注册</a>
                    {% endif %}
                </div>
                <div class="comment-area">
                    <h3 class="comment-area-title">评论列表</h3>
                    <div id="comment_list">
                        {% get_comment_list blog as comments %}
                        {% for comment in comments %}
                        <div  id="root_{{comment.pk}}" class="comment">
                            <span>
                                {{comment.user.get_nickname_or_username}}
                            </span>
                            <span>
                                ({{comment.comment_time|date:"y-m-d H:i:s"}}):
                            </span>
                            <div id="comment_{{comment.pk}}">
                                {{comment.comment_text|safe}}
                            </div>
                            <div class="like" onclick="like_change(this,'{% get_content_type comment %}',{{ comment.pk }})">
                                        <span class="glyphicon glyphicon-thumbs-up {% get_like_status comment %}"></span>
                                        <span class="liked-num">{% get_like_count comment %}</span>

                            </div>
                            <a href="javascript:reply_comment({{ comment.pk }});">回复</a>
                            {% for reply in comment.root_comment.all %}
                                <div class="reply">
                                    <span>
                                        {{reply.user.get_nickname_or_username}}
                                    </span>
                                    <span>
                                        ({{reply.comment_time|date:"y-m-d H:i:s"}})
                                    </span>

                                    <span>
                                         回复：
                                    </span>

                                    <span>{{ reply.reply_to.get_nickname_or_username }}</span>
                                    <div id="comment_{{ reply.pk }}">
                                        {{reply.comment_text|safe}}
                                    </div>
                                    <div class="like" onclick="like_change(this,'{% get_content_type reply %}',{{ reply.pk }})">
                                        <span class="glyphicon glyphicon-thumbs-up {% get_like_status reply %}"></span>
                                        <span class="liked-num">{% get_like_count reply %}</span>

                                    </div>
                                    <a href="javascript:reply_comment({{reply.pk}});">回复</a>
                                </div>
                            {% endfor %}
                        </div>
                        {% empty %}
                            <span id="no_comment">
                                没人想和你说话！
                            </span>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>



    </div>

{% endblock %}
{% block  script_extend %}
    <script type="text/javascript">

        //字符串占位符拼接
        String.prototype.format = function(){
            var str = this;
            for(var i = 0;i<arguments.length;i++){
                var str = str.replace(new RegExp('\\{'+i+'\\}','g'),arguments[i]);

            };
            return str;
        }
        $("#comment_form").submit(function () {
            //判断是否为空
            $("#comment_error").text('');
            if (CKEDITOR.instances['id_text'].document.getBody().getText().trim==''){
                $("#comment_error").text('评论内容不能为空');
                return false;
            }

            //更新数据到textarea
            CKEDITOR.instances['id_text'].updateElement();
            //异步提交
            $.ajax({
                url:"{% url 'comment:upload_comment' %}",
                type:'POST',
                data: $(this).serialize(),
                cache: false,
                success:function (data) {
                    console.log(data);
                    if(data['status'] =="SUCCESS"){
                        //插入数据

                        if ($('#reply_comment_id').val()=='0'){
                            //插入评论,
                            //var comment_html = '<div id="root_'+data['pk']+'"class="comment"><span>'+data['username']+'</span><span>(' +data['comment_time']+'):</span><div id="comment_'+data['pk']+'">'+data['text']+'</div><a href="javascript:reply_comment('+data['pk']+');">回复</a></div>';
                            var comment_html ='<div  id="root_{0}" class="comment"><span>{1}</span><span>({2}):</span><div id="comment_{0}">{3}</div><div class="like" onclick="like_change(this,\'{4}\',{0})"><span class="glyphicon glyphicon-thumbs-up"></span><span class="liked-num">0</span></div><a href="javascript:reply_comment({0});">回复</a></div>'
                            comment_html = comment_html.format(data['pk'],data['username'],data['comment_time'],data['text'],data['content_type']);
                            $("#comment_list").prepend(comment_html);
                        }else{
                            //var reply_html ='<div class="reply"><span>'+data['username']+'</span><span>(' +data['comment_time']+'):</span><span>回复 </span><span>'+data['reply_to']+':</span> <div id="comment_'+data['pk']+'">'+data['text']+'</div><a href="javascript:reply_comment('+data['pk']+');">回复</a></div>';
                            var reply_html ='<div class="reply"><span>{1}</span><span>({2}):</span><span>回复</span><span>{3}</span><div id="comment_{0}">{4}</div><div class="like" onclick="like_change(this,\'{5}\',{0})"><span class="glyphicon glyphicon-thumbs-up"></span><span class="liked-num">0</span></div><a href="javascript:reply_comment({0});">回复</a></div>'
                            reply_html = reply_html.format(data['pk'],data['username'],data['comment_time'],data['reply_to'],data['text'],data['content_type']);
                            $("#root_"+data['root_pk']).append(reply_html);
                        }

                        // 清空编辑器的内容
                        CKEDITOR.instances['id_text'].setData('');
                        $('#reply_content_container').hide();
                        $('#reply_comment_id').val('0');
                        $('#no_comment').remove();
                        $("#comment_error").text('评论成功');
                    }else{
                        //显示错误信息
                        $("#comment_error").text(data['message']);
                    }
                },
                error:function (xhr) {
                    console.log(xhr);
                }
            });
            return false
        }); //jquery的选择器，表示选中id为comment_form的form表单
        function reply_comment(reply_comment_id) {
            //设置值
            $('#reply_comment_id').val(reply_comment_id);
            var html =$("#comment_" +reply_comment_id).html();
            $('#reply_content').html(html);
            $('#reply_content_container').show();

            $('html').animate({scrollTop:$('#comment_form').offset().top -60 },300,function () {
                CKEDITOR.instances['id_text'].focus();
            });
        }
        function like_change(obj,content_type,object_id) {
            var is_like =obj.getElementsByClassName('active').length==0;
            $.ajax({
                url:"{% url 'likes:like_change' %}",
                type:'GET',
                data:{
                    content_type:content_type,
                    object_id:object_id,
                    is_like:is_like
                },
                cache:false,
                success:function (data) {
                    console.log(data)
                    if(data['status'] == 'SUCCESS'){
                        //更新点赞状态
                        var element = $(obj.getElementsByClassName('glyphicon-thumbs-up'));
                        if(is_like){
                            element.addClass('active');
                        }else{
                            element.removeClass('active');
                        }
                        //更新点赞数量
                        var liked_num = $(obj.getElementsByClassName('liked-num'));
                        console.log(data['liked_num'])
                        liked_num.text(data['liked_num']);
                    }
                    else {
                        if(data['code']=400){
                            $('#login_Modal').modal('show');
                        }else{
                            alert(data['message']);
                        }

                    }
                },
                error:function (xhr) {
                    console.log(xhr)
                },
            })
        }

    </script>
{% endblock %}

myblog/templates/myblog/blog_list.html
{#使用模板嵌套进行重新编写,要注意模板的相对路径#}
{% extends 'base.html' %}
{% load static %}
{% load comment_tags %}
{% load likes_tags %}
{% block header_content %}
<link rel ="stylesheet" href="{% static 'myblog/style/blog.css' %}">
{% endblock%}
{% block title %}
    {#页面标题，填充题目#}
    我的网站
{% endblock %}

{% block nav_blog_active %}active{%endblock%}

{% block content %}
<div class="container">
        {#8+4#}
        <div class="row">
             <div class=" col-sm-8 col-lg-10">
                 <div class="panel panel-info">
                     <div class="panel-heading">
                         {% block base_list_title %}<h2>博客列表</h2>{% endblock %}
                     </div>
                     <div class="panel-body">
                         {% for blog in page_of_blogs.object_list %}  <!--标签-->
                            <div class="blog">
                                <!-- 标题图 -->

                                    <div class="col-1" >
                                        <br>
                                    {# 获取每一个封面的url链接 #}
                                        <img src="{{ blog.avator.url }}"
                                             alt="avator"
                                             style="max-width:65%; border-radius: 20px;">
                                    </div>
                                <!-- 其他相关信息-->
                                <div class="col-2">
                                    <h3>
                                    <a href="{% url 'myblog:blog_detail' blog.id %}">
                                        {{ blog.title }}
                                    </a>
                                </h3>
                                <p class="blog-info" style="margin-right: 2em;">
                                    <span class="glyphicon glyphicon-tag" aria-hidden="true"></span> 分类：
                                    <a href="{%url 'myblog:blogs_with_type' blog.blog_type.pk%}">
                                       {{blog.blog_type}}
                                    </a>
                                    <br>
                                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>

                                    发表日期：{{blog.created_time|date:"Y-m-d H:i:s"}}
                                    <br>
                                    <span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span>
                                    阅读({{blog.get_read_num}})
                                    <span>评论({% get_comment_count blog %})</span>
                                    <span>点赞({% get_like_count blog%})</span>
                                </p>
                                <p>{{blog.content|striptags| truncatechars:10}}</p> <!-- striptags用于去除html标签， “|”的意思是过滤器 ,truncate:缩短，只显示前几个字符内容,一个汉字两个字符-->
                                </div>
                            </div>
                         {%empty%}
                            <div class="blog">
                                <h3>--暂无博客，敬请期待😁--</h3>
                            </div>
                         {% endfor %}
                     </div>
                 </div>
                 <div  class="paginator" aria-label="Page navigation">
                     <ul class="pagination">


                        {# 前一页 #}
                        <li>
                            {% if page_of_blogs.has_previous %}
                                <a href="?page={{ page_of_blogs.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            {% else %}
                                    <span aria-hidden="true">&laquo;</span>
                            {% endif %}
                        </li>

                        {% for page_num in page_range %}  {# 这里用到了类属性 #}
                            {% if page_num == page_of_blogs.number %}
                                {# 如果是当前页，就呈现出高亮显示 #}
                                <li class="active"><a href="?page={{ page_num}}">{{ page_num }}</a></li>
                            {% elif page_num == '...' %}
                                <li ><span>{{ page_num }}</span></li>
                            {% else %}
                                <li ><a href="?page={{ page_num}}">{{ page_num }}</a></li>
                            {% endif %}
                        {% endfor %}


                        {# 后一页 #}
                        <li>
                            {% if page_of_blogs.has_next %}
                                <a href="?page={{ page_of_blogs.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            {% else %}
                                    <span aria-hidden="true">&raquo;</span>
                            {% endif %}
                        </li>
                     </ul>
                     <p>
                         共有{{page_of_blogs.paginator.count}}篇博客,
                         当前第{{ page_of_blogs.number }}页
                         共{{page_of_blogs.paginator.num_pages }}页
                     </p>
                </div>

             </div>
             <div class="col-sm-4 col-lg-2">
                 <div class="panel panel-info">
                      <div class="panel-heading">
                          <h3 class="panel-title">
                            博客分类
                          </h3>
                      </div>
                      <div class="panel-body">
                        <ul  class="blog-types" >
                            {% for blog_type in blog_types %}
                                <li>
                                    <a href="{%url 'myblog:blogs_with_type' blog_type.pk%}">
                                        {{ blog_type.type_name }}({{blog_type.blog_count}})
                                    </a>
                                </li>
                                {%empty%}
                                <li>
                                    --暂无分类✈--
                                </li>
                            {% endfor %}
                        </ul>
                      </div>
                 </div>
                 <div class="panel panel-info">
                      <div class="panel-heading">
                          <h3 class="panel-title">
                            日期归档
                          </h3>
                      </div>
                      <div class="panel-body">
                        <ul>
                            {% for blog_month_date,blog_count in blog_dates.items %}
                            <li>
                                <a href="{% url 'myblog:blogs_with_date' blog_month_date.year blog_month_date.month %}" >
                                    {{ blog_month_date| date:"Y年m月"}}({{ blog_count }})
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                      </div>
                 </div>
             </div>
        </div>
    </div>
{% endblock %}

myblog/templates/myblog/blogs_with_date.html
{#使用模板嵌套进行重新编写#}
{% extends 'myblog/blog_list.html' %}
{% block title %}
    {#页面标题，填充题目#}
    {{blog_type.type_name}}
{% endblock %}

{% block base_list_title %}
    <span>日期归档：{{blogs_with_date}}</span>
    <span class="pull-right">
        <a href="{% url 'myblog:blog_list' %}">查看全部博客</a>
    </span>
{% endblock %}

myblog/templates/myblog/blogs_with_type.html
{#使用模板嵌套进行重新编写#}
{% extends 'myblog/blog_list.html' %}
{% block title %}
    {#页面标题，填充题目#}
    {{blog_type.type_name}}
{% endblock %}

{% block base_list_title %}
    <span>分类：{{blog_type.type_name}}</span>
    <span class="pull-right">
        <a href="{% url 'myblog:blog_list' %}">查看全部博客</a>
    </span>

{% endblock %}