myblog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'myblog'
urlpatterns = [
    url(r'^$', views.blog_list, name='blog_list'),
    url(r'^(?P<blog_pk>[0-9]+)/$', views.blog_detail, name='blog_detail'),
    url(r'^type/(?P<blog_type_pk>[0-9]+)/$', views.blogs_with_type, name='blogs_with_type'),
    url(r'^date/(?P<year>[0-9]+)/(?P<month>[0-9]+)',views.blogs_with_date, name ='blogs_with_date')

]
#将根urlconf指向polls.urls模块
#该url函数传递了四个参数，两个必须：route 和view ，以及两个可选kwargs和name
    #route参数：使用正则表达式进行捕获和匹配
        # 术语 “regex” 是正则表达式 “regular expression” 的缩写，是匹配字符串的一段语法，像这里例子的是 url 匹配模式。Django 从列表的第一个正则表达式开始，按顺序匹配请求的 URL，直到找到与之匹配的。
        # 注意，这些正则表达式不会去匹配 GET 和 POST 请求的参数值，或者域名。
        # 比如 https://www.example.com/myapp/ 这个请求，URLconf 会找 myapp/；https://www.example.com/myapp/?page=3 这个请求，URLconf 同样只会找 mysqpp/。
        #这些正则表达式在 URLconf 模块加载后的第一时间就被编译了
    #view参数
        # 当Django发现一个正则表达式匹配时，Django就会调用指定的视图函数，
        # HttpRequest对象作为第一个参数，正则表达式捕获的值作为其他参数。如果正则使用简单捕获，值会作为位置参数传递；
        # 如果使用命名捕获，值会作为关键字传递。我们稍后会给出一个例子。
    # name参数
        #命名你的URL可以让你在Django的别处明白引用的是什么，特别是在模版里。
        #这个强大的特性允许你在项目里对一个文件操作就能对URL模式做全局改变。

user/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('login/', views.login_user, name='login_user'),
    path('login_for_modal/', views.login_for_modal, name='login_for_modal'),
    path('register/', views.register_user, name='register_user'),
    path('logout/', views.logout, name="logout"),
    path('user_info/', views.user_info, name="user_info"),
    path('change_nickname/',views.change_nickname,name = "change_nickname"),
    path('bind_email/',views.bind_email,name = "bind_email"),
    path('send_verification_code/',views.send_verification_code,name = "send_verification_code"),
    path('change_password/',views.change_password,name = "change_password"),
    path('forgot_password/',views.forgot_password,name = "forgot_password"),
]

templates/back_to_top_func.html
<!-- 参考了 鹦鹉 的代码，在此致谢 -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->

<!-- 参考了杜赛的知乎文章，在此致谢：https://zhuanlan.zhihu.com/p/62136369 -->

<button type="button" id="BackTop" class="toTop-arrow" style="z-index:100;">
    <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>
</button>

<script type="text/javascript">
    //向上滚动的函数,涉及到了Jquery语法，监听两个事件：
    //用户点击浮动按钮，将页面上滚至顶部
    //当页面滚动时，根据页面距离顶部的距离，决定按钮显示或隐藏
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop:0},500);
        });
        $(window).scroll(function () {
            if($(this).scrollTop()>100){
                $('#BackTop').fadeIn(100);
            } else {
                $('#BackTop').stop().fadeout(100);
            }
        }).scroll();
    });
</script>


<style type="text/css">
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */

</style>

templates/base.html
<!DOCTYPE html>
{#模板嵌套#}
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">  {# 根据屏幕自动调整适应相关布局#}
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel = "stylesheet" type = "text/css" href="{% static 'style/base.css' %}"/>
    <link rel = "stylesheet" type = "text/css" href="{% static 'bootstrap3.7/css/bootstrap.min.css' %}">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script type="text/javascript" src="{% static 'script/jquery-1.12.4.min.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'bootstrap3.7/js/bootstrap.min.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js'  %}"></script>
    {% block header_content %}{% endblock%}
    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    {% include 'back_to_top_func.html' %}
    {% include 'header.html' %}
    <!-- 新增两个 div 容器 -->
    <!--#push容器留出一段与页脚等高的空隙，避免正文内容与页脚重叠。-->
    <!--#wrapper容器的底部有一个负边距，作用是给页脚容器让出位置。-->
    <div id="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>
    {% block  script_extend %}{% endblock %}
    {% include 'footer.html' %}
</body>
</html>

templates/error.html
{#使用模板嵌套进行重新编写,要注意模板的相对路径#}

{% extends 'base.html' %}
{%load staticfiles%}
{% block title %}
    王晟的个人网站|错误
{% endblock %}

{% block header_content %}
         <link rel = "stylesheet" type = "text/css" href="{% static 'style/home.css' %}"/>
         <script type="text/javascript" src="{% static 'script/echarts.js' %}" charset="utf-8"></script>
{% endblock%}

{% block nav_home_active %}active{%endblock%}

{% block content %}
   {{ message }}，<a href="{{redirect_to}}">返回之前博客</a>
{% endblock %}

templates/footer.html
{% load staticfiles %}
<!-- Footer 页脚底部备案-->
<div class="footer">
    <div class="website-info">
        <p>晋ICP备19002929号-1 Copyright© www.nihaogis.com 2019</p>
        <p>意见反馈或合作请联系我(ws260308526519@163.com💌)</p>
    </div>
</div>

templates/form.html
{#使用模板嵌套进行重新编写,要注意模板的相对路径#}

{% extends 'base.html' %}
{%load staticfiles%}
{% block title %}
    {{ page_title }}
{% endblock %}

{% block header_content %}
         <link rel = "stylesheet" type = "text/css" href="{% static 'style/home.css' %}"/>
         <script type="text/javascript" src="{% static 'script/echarts.js' %}" charset="utf-8"></script>
{% endblock%}

{% block nav_home_active %}active{%endblock%}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{form_title}}</h3>
                </div>
                <div class="panel-body">
                    <form action="" method="POST">  {# "#"表示提交数据到本页面 #}
                        {% csrf_token %}

                        {% for field in form %}   {#这一句会自动生成html代码：用户和密码#}
                            {% if not field.is_hidden %}
                                <label for="{{field.id_for_label}}}">{{field.label}}</label>
                            {% endif  %}
                            {{ field }}
                            <p class="text-danger">
                                {{field.errors.as_text}}
                            </p>
                        {% endfor %}
                        <span id="error_tip" class = "pull-left text-danger">
                            {%for error in form.non_field_errors %}
                                {{error}}
                            {% endfor %}
                        </span>
                        <div class="clearfix"></div>
                        <div class="pull-left">
                            {% block other_buttons %}{%endblock%}
                        </div>
                        <div class="pull-right">
                            <input type="submit"  class="btn btn-primary" value = "{{submit_text}}">
                            <button class="btn btn-default" onclick="window.location.href='{{ retrun_back_url }}'">返回</button>
                        </div>

                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/header.html
<!--对base页面进行进一步的拆分，此html是页面顶部导航栏部分-->
<div class="navbar navbar-default navbar-fixed-top" role ="navigation">
        <div class="contain-fluid">{#导航条撑满整个页面#}
            <div class="navbar-header">
                <a class = "navbar-brand" href="/">
                    个人博客网站
                </a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="{% block nav_home_active %}{% endblock %}">
                        <a href="/">
                            首页
                        </a>
                    </li>
                    <li class="{% block nav_blog_active %}{% endblock %}">
                        <a href="{% url 'myblog:blog_list' %}">
                            博客
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if not user.is_authenticated %}
                        <li>
                            <a  href ="{% url 'login_user' %}?from={{ request.get_full_path }}">登录</a>
                        </li>
                        <li style="margin-right: 40px">
                            <a  href ="{% url 'register_user' %}?from={{ request.get_full_path }}">注册</a>
                        </li>
                    {% else %}
                    <li class="dropdown" style="margin-right: 40px">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                          {% if user.has_nickname %}
                            {{ user.username }}({{ user.get_nickname }})
                          {% else %}
                            {{ user.username}}
                          {% endif %}
                          <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'user_info'%}">个人资料</a></li>
                        <li role="separator" class="divider"></li>      {#分割线#}
                        <li><a href="{% url 'change_password' %}">修改密码</a></li>
                        <li role="separator" class="divider"></li>      {#分割线#}
                        {% if user.is_staff or user.is_superuser %}
                            <li><a href="{% url 'admin:index'%}">后台管理</a></li>
                            <li role="separator" class="divider"></li>      {#分割线#}
                        {% endif %}

                        <li><a href="{% url 'logout'%}">退出</a></li>
                      </ul>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
</div>




<!-- Modal -->
<div class="modal fade" id="login_Modal" tabindex="-1" role="dialog" >
          <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <form id="login_modal_form" action="" method="POST">  {# "#"表示提交数据到本页面 #}
                          <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" >登录</h4>
                          </div>
                          <div class="modal-body">
                            {% csrf_token %}

                            {% for field in login_modal_form %}   {#这一句会自动生成html代码：用户和密码#}
                                <label for="{{field.id_for_label}}}">{{field.label}}</label>
                                {{ field }}
                            {% endfor %}
                            <span  id="login_modal_tip" class = "text-danger">
                            </span>
                          </div>
                          <div class="modal-footer">
                                <button type="submit" class="btn btn-default" >登录</button>
                                <button type="button" class="btn btn-primary" data-dismiss="modal">关闭</button>
                          </div>
                    </form>
                    </div>
          </div>
    </div>


<script type="text/javascript">
        $("#login_modal_form").submit(function (event) {
        event.preventDefault();
        $.ajax({
            url:"{% url 'login_for_modal' %}",
            type:'POST',
            async : false,
            data:$(this).serialize(),
            cache:false,
            success:function (data) {
                console.log(data)
                if(data['status']=="SUCCESS"){
                    window.location.reload();//当前窗口刷新重载
                }else{
                    $('#login_modal_tip').text('用户名或密码不正确')
                }
            }
        });
    });
</script>

templates/home.html
{#使用模板嵌套进行重新编写,要注意模板的相对路径#}

{% extends 'base.html' %}
{%load staticfiles%}
{% block title %}
    王晟的个人网站|首页
{% endblock %}

{% block header_content %}
         <link rel = "stylesheet" type = "text/css" href="{% static 'style/home.css' %}"/>
         <script type="text/javascript" src="{% static 'script/echarts.js' %}" charset="utf-8"></script>
{% endblock%}

{% block nav_home_active %}active{%endblock%}

{% block content %}
    <h1 class = "home-content">欢迎来到你好，GIS网站</h1>
     <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="container" style="width: 600px;height:400px;"></div>
    <div class="hot-data">
        <!-- 今天24小时内的热门博客-->
        <h3>
            今日热门点击
        </h3>
        <ul>
            {% for hot_data in today_hot_data %}
               <li>
                    <a href="{% url 'myblog:blog_detail' hot_data.id %}">
                    {{ hot_data.title }}
                    </a>
                    ({{ hot_data.read_num_sum }})
                </li>
            {% empty %}
                <li>
                    扎心了，没人看，无热门。。。
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="hot-data">
        <!-- 昨天24小时内的热门博客-->
        <h3>
            昨日热门点击
        </h3>
        <ul>
            {% for hot_data in yesterday_hot_data %}
                <li>
                    <a href="{% url 'myblog:blog_detail' hot_data.id %}">
                    {{ hot_data.title }}
                    </a>
                    ({{ hot_data.read_num_sum }})
                </li>
            {% empty %}
                <li>
                    扎心了，没人看，无热门。。。
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="hot-data">
        <h3>
        一周热门点击
        </h3>
        <ul>
            {% for hot_data in weekly_hot_data %}
                <li>
                    <a href="{% url 'myblog:blog_detail' hot_data.id %}">
                    {{ hot_data.title }}
                    </a>
                    ({{ hot_data.read_num_sum }})
                </li>
            {% empty %}
                <li>
                    扎心了，没人看，无热门。。。
                </li>
            {% endfor %}
        </ul>
    </div>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('container'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: null
            },
            tooltip: {},
            legend: {
                data:['七天阅读量']
            },

            xAxis: {
                axisTick:{
                  alignWithLabel: true,
                },
                data: {{ dates|safe }},

            },
            yAxis: {
                show:false,
            },
            series: [{
                name: '七天阅读量',
                type: 'line',
                label:{
                    show:true
                },
                markPoint: {
                data: [
                    {type: 'max', name: '最大值'},
                    {type: 'min', name: '最小值'}
                ]
                },

                data: {{ read_nums }},

            }]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>

{% endblock %}